### ISSUE TITLE
Exception in nim 1.2.2

### ISSUE THREAD

**Issue by rishavs** [Nycto/AStarNim#4]
Using astar in latest nim 1.2.2 is throwing an exception
`        ... C:\Users\risharan\.nimble\pkgs\astar-0.4.0\astar.nim(25, 22) Error: undeclared identifier: 'THash'`

**Comment by Nycto** [comment]
Looks like version 0.6.0 was never published. I've done this now. Try updating your dependency and see if that fixes the problem.

**Comment by rishavs** [comment]
Thanks. Can confirm that the issue is now resolved.
